server:
  error:
    include-stacktrace: on_param
logging:
  config=classpath:logback.xml
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: update
              create-target: src/main/resources/db/dll_db.sql
  datasource:
    url: jdbc:mysql://localhost:3306/graph_db?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000

  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/callback
